version: '{build}'
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      IMAGE_NAME: win
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      IMAGE_NAME: ubuntu-18.04-bionic
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
      IMAGE_NAME: ubuntu-16.04-xenial
skip_commits:
  files:
    - '*.md'
    - '*.txt'
branches:
  only:
    - master
  except:
    - /.+[\-.]wip$/
    - wip
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
build_script:
  - cmd: call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmd: build.cmd
  - sh: ./build.sh
after_build:
  - cmd: 7z a -tzip elvee-%IMAGE_NAME%.zip LICENSE elvee.exe
  - sh: tar cfz elvee-${IMAGE_NAME}.tar.gz LICENSE elvee
artifacts:
  - path: '*.zip'
  - path: '*.tar.gz'
notifications:
- provider: Email
  to:
  - raboof-ci@googlegroups.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
